#¿Qué es NumPy?

NumPy (Numerical Python) es una biblioteca de Python especializada en el cálculo numérico, que facilita la creación y manipulación de arrays y matrices de múltiples dimensiones. Esta biblioteca proporciona el objeto ndarray, que es una estructura de datos eficiente para almacenar y operar con matrices n-dimensionales. NumPy incluye una amplia gama de funciones para realizar operaciones matemáticas y de álgebra lineal, facilitando el procesamiento y análisis de datos numéricos siendo fundamental para la ciencia de datos, análisis estadístico, y otras aplicaciones cientificas. Esta biblioteca es la base para construir otras como  `Pandas, Scipy, Matplotlib, Scikit-learn, etc. `








Estos arreglos de NumPy tiene algunas caracteristicas:
1. Tiene tamaño fijo. Cuando se cambia el tamaño se borra y se crea una nuevo.
2. Elementos del mismo tipo de dato.
3. Soportan o facilitan el uso de operaciones matemáticas.

#¿Cómo importar NumPy?

En Python, para importar bibliotecas se utiliza la palabra `import` seguido del nombre de esta misma además es común asignarles un prefijo utilizando `as`. Esto facilita el acceso a las funciones y clases dentro de la biblioteca.

Por ejemplo, al importar NumPy, se suele utilizar:

In [ ]:
import numpy as np

# Mis primeros pasos

Para crear un `ndarray` usamos el método `.array()` a partir de una lista.

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

Podemos acceder a los elemento de la matriz utilizando el índice entero del elemento entre corchetes.

In [ ]:
# Recuerda que el índice en python inicia en 0.
A[1]

array([3, 4])

Otra forma de consultar los elementos de una matriz es utilizando la notación de corte. La sintaxis `a[n:m]` devuelve los elementos desde el índice inicial `n` hasta el índice final `m-1`.

In [ ]:
a[3:5]

array([4, 5])

Se pueden inicializar matrices bidimensionales y de dimensiones superiores a partir de listas anidadas

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[8, 7, 6, 5], [4, 3, 2, 1]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [ ]:
c.shape

(2, 2, 4)

In [ ]:
c[1]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [ ]:
c[1,0]

array([8, 7, 6, 5])

In [ ]:
c[1,0,3]

5

También podemos seleccionar aquellos elementos que satisfacen una condición específica

In [ ]:
b[b<8]

array([1, 2, 3, 4, 5, 6, 7])

## Atributos de una matriz

Podemos consultar la dimensión de la matriz

In [ ]:
c.ndim

3

In [ ]:
b.ndim

2

La forma de la matriz que nos da la cantidad de elementos a lo largo de cada dimensión

In [ ]:
b.shape

(3, 4)

El número total de elementos

In [ ]:
b.size

12

El tipo de dato que contiene

In [ ]:
b.dtype

dtype('int64')

Incluso podemos modificar las dimensiones de una matriz

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Notemos que la matriz original no se modifica

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## ¿Cómo crear una matriz básica?

Matriz de ceros

In [ ]:
np.zeros((5,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

Matriz de unos

In [ ]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Matriz Identidad

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Podemos crear una matriz con un rango de elementos

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

Incluso una matriz que contenga un rango de intervalos espaciados uniformemente.

`np.arange(**primer número**, **último número**, **tamaño de salto**)`

In [ ]:
np.arange(1,9,3)

array([1, 4, 7])

Podemos usar también np.linspace() para crear una matriz con valores espaciados linealmente en un intervalo especificado.

`np.linspace(**primer número**, **último número**, **tamaño de elementos**)`



In [ ]:
np.linspace(1,9,3)

array([1., 5., 9.])

Matriz con números aleatorios provenientes de una distribución $N(0, 1)$

In [ ]:
np.random.normal(loc = 1.7, scale = 0.5, size=100)

array([1.88171377, 1.83719398, 1.0818559 , 1.13302548, 2.31176859,
       1.17062577, 1.7860863 , 1.73209148, 1.88936581, 1.97765038,
       1.46763547, 1.62758792, 1.0915608 , 2.17933688, 1.95045747,
       1.51825323, 0.55002986, 1.82110199, 1.60637401, 1.40224625,
       2.92891529, 1.84658009, 1.61594881, 1.99760808, 1.48450481,
       1.93258146, 2.24894953, 3.12380801, 1.58298967, 2.46941015,
       1.93950689, 1.62959688, 1.33422175, 1.22169051, 0.85378781,
       1.54751771, 1.86700324, 0.98416225, 0.94660856, 1.70638722,
       1.73651319, 2.20823882, 1.54577585, 1.80487673, 1.79185092,
       1.38603086, 1.00523573, 1.68109527, 1.74015878, 1.53929669,
       0.92993348, 1.66514216, 1.8623577 , 1.85479225, 1.03650054,
       1.2147287 , 1.25680391, 2.35902883, 1.62267476, 0.9212885 ,
       2.3530958 , 1.71288793, 1.98188417, 2.2329526 , 1.95257492,
       2.404362  , 2.2677286 , 2.09464928, 1.54838794, 1.95681956,
       2.1261313 , 1.97997632, 1.74309037, 2.13187015, 1.75829

In [ ]:
np.random.rand(3,2)

array([[0.72508411, 0.82496597],
       [0.34225048, 0.88601346],
       [0.27514608, 0.95699627]])

Matriz con números enteros aleatorios provenientes de un intervalo

In [ ]:
np.random.randint(1,50,(2,5))

array([[49, 49, 48, 32, 49],
       [ 7, 15,  6, 49,  3]])

## Agregar, eliminar y ordenar elementos

In [ ]:
x = np.random.randint(1,50,(3,5))
x

array([[42,  3, 27, 23, 42],
       [38, 44, 19,  8, 29],
       [34, 34, 24, 15, 45]])

In [ ]:
y = np.random.randint(1,50,(3,5))
y

array([[32, 17, 32, 14, 22],
       [25,  1,  2, 29, 43],
       [29, 18, 34,  6, 26]])

Para ordenar los valores de la matriz

In [ ]:
np.sort(x)

array([[ 3, 23, 27, 42, 42],
       [ 8, 19, 29, 38, 44],
       [15, 24, 34, 34, 45]])

Concatenar matrices

In [ ]:
np.concatenate((x,y))

array([[42,  3, 27, 23, 42],
       [38, 44, 19,  8, 29],
       [34, 34, 24, 15, 45],
       [32, 17, 32, 14, 22],
       [25,  1,  2, 29, 43],
       [29, 18, 34,  6, 26]])

Para apilar dos matrices existentes, tanto vertical como horizontal.

In [ ]:
np.vstack((x,y))

array([[42,  3, 27, 23, 42],
       [38, 44, 19,  8, 29],
       [34, 34, 24, 15, 45],
       [32, 17, 32, 14, 22],
       [25,  1,  2, 29, 43],
       [29, 18, 34,  6, 26]])

In [ ]:
np.hstack((x,y))

array([[42,  3, 27, 23, 42, 32, 17, 32, 14, 22],
       [38, 44, 19,  8, 29, 25,  1,  2, 29, 43],
       [34, 34, 24, 15, 45, 29, 18, 34,  6, 26]])

Puedes encontrar los elementos únicos en una matriz fácilmente con np.unique

In [ ]:
np.unique(x)

array([ 3,  8, 15, 19, 23, 24, 27, 29, 34, 38, 42, 44, 45])

In [ ]:
x

array([[42,  3, 27, 23, 42],
       [38, 44, 19,  8, 29],
       [34, 34, 24, 15, 45]])

Transponer una matriz

In [ ]:
x.transpose()

array([[42, 38, 34],
       [ 3, 44, 34],
       [27, 19, 24],
       [23,  8, 15],
       [42, 29, 45]])

In [ ]:
x.T

array([[42, 38, 34],
       [ 3, 44, 34],
       [27, 19, 24],
       [23,  8, 15],
       [42, 29, 45]])

Invertir una matriz

In [ ]:
np.flip(x)

array([[45, 15, 24, 34, 34],
       [29,  8, 19, 44, 38],
       [42, 23, 27,  3, 42]])

## Funciones

In [ ]:
d = np.random.randint(1,10,(3,3))
d

array([[5, 2, 9],
       [1, 3, 7],
       [1, 6, 1]])

Sumar todos los elementos de la matriz.

In [ ]:
d.sum()

35

In [ ]:
np.sum(d)

35

Sumar elementos por fila

In [ ]:
d.sum(axis=1)

array([16, 11,  8])

Sumar elementos por columna

In [ ]:
d.sum(axis=0)

array([ 7, 11, 17])

Encontrar el valor mínimo

In [ ]:
d.min(axis=1)

array([2, 1, 1])

Determinar la posición del valor mínimo del arreglo




In [ ]:
d.argmin()

3

Encuentra el valor máximo de la matriz

In [ ]:
d.max()

9

Determina la posición del valor máximo de la matriz

In [ ]:
d.argmax()

2

Calcula la desviación estándar de los valores de la matriz

In [ ]:
d.std()

2.806517986736686

In [ ]:
d.mean()

3.888888888888889

# Modificar elementos

Realmente lo que sucede es que se borra el anterior objeto y se crea uno nuevo.

In [ ]:
d

array([[5, 2, 9],
       [1, 3, 7],
       [1, 6, 1]])

In [ ]:
d[1,1] = 0

In [ ]:
d

array([[5, 2, 9],
       [1, 0, 7],
       [1, 6, 1]])

# Operaciones básicas con matrices

In [ ]:
e = np.random.randint(1,100,(3,3))
e

array([[85, 26,  8],
       [83, 78, 75],
       [40, 30, 52]])

In [ ]:
f = np.random.randint(1,100,(3,3))
f

array([[78, 16, 92],
       [91, 43,  4],
       [70, 55,  2]])

Suma

In [ ]:
e+f

array([[163,  42, 100],
       [174, 121,  79],
       [110,  85,  54]])

Resta

In [ ]:
e-f

array([[  7,  10, -84],
       [ -8,  35,  71],
       [-30, -25,  50]])

Multiplicación

In [ ]:
e*f

array([[6630,  416,  736],
       [7553, 3354,  300],
       [2800, 1650,  104]])

In [ ]:
np.matmul(e,f)

array([[3692, 7352, 6558],
       [3022, 3098, 2480],
       [3355, 7932, 5979]])

Exponente

In [ ]:
e**2

array([[ 100,  676, 4356],
       [  16, 1600,  324],
       [2304, 1089, 1156]])

Raíz Cuadrada

In [ ]:
np.sqrt(e)

array([[3.16227766, 5.09901951, 8.1240384 ],
       [2.        , 6.32455532, 4.24264069],
       [6.92820323, 5.74456265, 5.83095189]])

Función exponencial

In [ ]:
np.exp(e)

array([[2.20264658e+04, 1.95729609e+11, 4.60718663e+28],
       [5.45981500e+01, 2.35385267e+17, 6.56599691e+07],
       [7.01673591e+20, 2.14643580e+14, 5.83461743e+14]])

Función Seno

In [ ]:
np.sin(e)

array([[-0.54402111,  0.76255845, -0.02655115],
       [-0.7568025 ,  0.74511316, -0.75098725],
       [-0.76825466,  0.99991186,  0.52908269]])

Función Coseno

In [ ]:
np.cos(e)

array([[-0.83907153,  0.64691932, -0.99964746],
       [-0.65364362, -0.66693806,  0.66031671],
       [-0.64014434, -0.01327675, -0.84857027]])

Logaritmo

In [ ]:
np.log(e)

array([[2.30258509, 3.25809654, 4.18965474],
       [1.38629436, 3.68887945, 2.89037176],
       [3.87120101, 3.49650756, 3.52636052]])

Producto Punto

In [ ]:
g =  np.random.randint(1, 5, (1, 3))
h = np.random.randint(1, 7, (3, 1))
np.dot(g, h)

array([[24]])

# Álgebra Lineal con Numpy

NumPy contiene un submódulo llamado numpy.linalg que proporciona funciones para realizar operaciones de álgebra lineal, como el cálculo de inversas de matrices, determinantes, y sistemas de ecuaciones lineales.

Iniciemos elevando una matriz cuadrada a la potencia n.

In [ ]:
g = np.random.randint(1,10,(3,3))
g

array([[7, 1, 9],
       [6, 3, 3],
       [7, 4, 3]])

In [ ]:
# Opción 1
from numpy.linalg import matrix_power

In [ ]:
matrix_power(g, 2)

array([[118,  46,  93],
       [ 81,  27,  72],
       [ 94,  31,  84]])

In [ ]:
matrix_power(g, 0)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# Opción 2
np.linalg.matrix_power(g, 2)

array([[118,  46,  93],
       [ 81,  27,  72],
       [ 94,  31,  84]])

In [ ]:
np.linalg.matrix_power(g, 0)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Determinante**

In [ ]:
np.linalg.det(g)

9.000000000000005

**Inversa**

In [ ]:
g_inv = np.linalg.inv(g)
g_inv

array([[-0.33333333,  3.66666667, -2.66666667],
       [ 0.33333333, -4.66666667,  3.66666667],
       [ 0.33333333, -2.33333333,  1.66666667]])

In [ ]:
g

array([[7, 1, 9],
       [6, 3, 3],
       [7, 4, 3]])

In [ ]:
M = np.matmul(g,g_inv)
M

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-15],
       [ 3.33066907e-16,  1.00000000e+00, -1.33226763e-15],
       [ 2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
np.round(M,2)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

**Valores propios y vectores propios**

In [ ]:
from numpy import linalg as LA

In [ ]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
valores_propios, vectores_propios = np.linalg.eig(np.array([[1, 0], [0, 2]]))

In [ ]:
valores_propios

array([1., 2.])

In [ ]:
vectores_propios

array([[1., 0.],
       [0., 1.]])

**Sistema de ecuaciones lineales**

$$\left( \begin{array}{c}
a \\
b  
\end{array}
\right)
 =
\left( \begin{array}{cc}
1 & 2 \\
3 & 5
\end{array}
\right)
\left( \begin{array}{c}
1  \\
2
\end{array}
\right)
$$

In [ ]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x


array([-1.,  1.])

## Tarea
Explorar las guias de usuario de las paqueterias
- Numpy
- Pandas
- Matplotlib